config/routes.rb
Precios::Application.routes.draw do

  resources :categoria_productos
  
  
  resources :productos do
    collection do 
      get :importar 
      post :importar_post
    end
  end

  resources :productos
  resources :proveedors
  resources :empresas

  devise_for :usuarios do get '/usuarios/sign_out' => 'devise/sessions#destroy', :path_prefix => 'my' end
  resources :usuarios
  match 'usuarios/:id' => 'usuarios#show'

  get "usuarios/index"
  get "home/index"

  root :to => 'home#index'

end

app/models/categoria_producto.rb
class CategoriaProducto < ActiveRecord::Base
  attr_accessible :estado, :nombre
  validates :nombre, :presence => { :message => ": Ingrese un valor." }
  has_many :productos
end

app/controllers/categoria_productos_controller.rb
class CategoriaProductosController < ApplicationController
  handles_sortable_columns
  # GET /categoria_productos
  # GET /categoria_productos.json
  def index
    order = sortable_column_order
    @categoria_productos = CategoriaProducto.order(order)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categoria_productos }
    end
  end

  # GET /categoria_productos/1
  # GET /categoria_productos/1.json
  def show
    @categoria_producto = CategoriaProducto.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @categoria_producto }
    end
  end

  # GET /categoria_productos/new
  # GET /categoria_productos/new.json
  def new
    @categoria_producto = CategoriaProducto.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @categoria_producto }
    end
  end

  # GET /categoria_productos/1/edit
  def edit
    @categoria_producto = CategoriaProducto.find(params[:id])
  end

  # POST /categoria_productos
  # POST /categoria_productos.json
  def create
    @categoria_producto = CategoriaProducto.new(params[:categoria_producto])

    respond_to do |format|
      if @categoria_producto.save
        format.html { redirect_to @categoria_producto, notice: 'Categoria producto was successfully created.' }
        format.json { render json: @categoria_producto, status: :created, location: @categoria_producto }
      else
        format.html { render action: "new" }
        format.json { render json: @categoria_producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categoria_productos/1
  # PUT /categoria_productos/1.json
  def update
    @categoria_producto = CategoriaProducto.find(params[:id])

    respond_to do |format|
      if @categoria_producto.update_attributes(params[:categoria_producto])
        format.html { redirect_to @categoria_producto, notice: 'Categoria producto was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @categoria_producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categoria_productos/1
  # DELETE /categoria_productos/1.json
  def destroy
    @categoria_producto = CategoriaProducto.find(params[:id])
    @categoria_producto.destroy

    respond_to do |format|
      format.html { redirect_to categoria_productos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/categoria_productos_helper.rb
module CategoriaProductosHelper
end

app/views/categoria_productos/_form.html.erb
<%= form_for(@categoria_producto) do |f| %>
  <% if @categoria_producto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@categoria_producto.errors.count, "error") %> prohibited this categoria_producto from being saved:</h2>

      <ul>
      <% @categoria_producto.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :nombre %><br />
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :estado %><br />
    <%= f.check_box :estado %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categoria_productos/edit.html.erb
<h1>Editing categoria_producto</h1>

<%= render 'form' %>

<%= link_to 'Show', @categoria_producto %> |
<%= link_to 'Back', categoria_productos_path %>

app/views/categoria_productos/index.html.erb
<h1>Listing categoria_productos</h1>

<table>
  <tr>
    <th>Nombre</th>
    <th>Estado</th>
    <th>Opciones</th>
  </tr>

<% @categoria_productos.each do |categoria_producto| %>
  <tr>
    <td><%= categoria_producto.nombre %></td>
    <td><%= categoria_producto.estado %></td>	  
    <td><%= link_to 'Show', categoria_producto %></td>
    <td><%= link_to 'Edit', edit_categoria_producto_path(categoria_producto) %></td>
    <td><%= link_to 'Destroy', categoria_producto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Categoria producto', new_categoria_producto_path %>

app/views/categoria_productos/new.html.erb
<h1>New categoria_producto</h1>

<%= render 'form' %>

<%= link_to 'Back', categoria_productos_path %>

app/views/categoria_productos/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_categoria_producto_path(@categoria_producto) %> |
<%= link_to 'Back', categoria_productos_path %>