config/routes.rb
Precios::Application.routes.draw do

  resources :categoria_productos
  
  
  resources :productos do
    collection do 
      get :importar 
      post :importar_post
    end
  end

  resources :productos
  resources :proveedors
  resources :empresas

  devise_for :usuarios do get '/usuarios/sign_out' => 'devise/sessions#destroy', :path_prefix => 'my' end
  resources :usuarios
  match 'usuarios/:id' => 'usuarios#show'

  get "usuarios/index"
  get "home/index"

  root :to => 'home#index'

end

app/models/producto.rb
class Producto < ActiveRecord::Base
  attr_accessible :concentracion_ing_activo, :estado, :proveedor_id, :categoria_producto_id, :ingrediente_activo, :nombre, :precio, :ultimo_update,
  :tipo_formula, :cantidad_unitaria, :unidad, :empaque_unitario, :precio_unitario 
  belongs_to :categoria_producto
  belongs_to :proveedor
  
  include Tire::Model::Search
  include Tire::Model::Callbacks
  
  mapping do
     indexes :nombre, :index => 'not_analyzed'
     indexes :proveedor_id, :index => 'not_analyzed'
     indexes :categoria_producto_id, :index => 'not_analyzed'
     indexes :ingrediente_activo, :index => 'not_analyzed'
     indexes :concentracion_ing_activo, :index => 'not_analyzed'
     indexes  :tipo_formula, :index => 'not_analyzed'
     indexes  :cantidad_unitaria, :index => 'not_analyzed'
     indexes  :unidad, :index => 'not_analyzed'
     indexes  :empaque_unitario, :index => 'not_analyzed'
     indexes  :precio, :index => 'not_analyzed'
     indexes  :precio_unitario, :index => 'not_analyzed'
     indexes  :ultimo_update, :index => 'not_analyzed'
     indexes  :estado, :index => 'not_analyzed'
  end
  def self.search(params)
    #binding.pry
    tire.search(load: true, page: params[:page], per_page: 20) do
      query { string params[:query] } if params[:query].present?
      #sort { by Producto.column_names.include?(params[:sort]) ? params[:sort] : :id ,%w[asc desc].include?(params[:direction]) ? params[:direction] : "desc"}

    end

    
  end
  
  #importar archivos csv 
  def self.importar_post(file)
    spreadsheet = open_spreadsheet(file)
    header = ["num_fila", "proveedor_id" , "categoria_producto_id", "nombre", "ingrediente_activo", "tipo_formula", "concentracion_ing_activo",
      "cantidad_unitaria", "unidad", "empaque_unitario", "precio", "precio_unitario", "ultimo_update"]
     
    (1..spreadsheet.last_row).each do |i|
      row = Hash[[header, spreadsheet.row(i)].transpose]
      #TODO: relacionar proveedor y categoria con sus respectivas tablas     
      #TODO: hacer un log de los datos de los productos que no se insertaron , y pq razon
      
      #row = limpiar_row(row)

      #TODO: agregar validacion por proveedor y por categoria producto
      producto = Producto.where("nombre is ? AND ingrediente_activo is ? AND tipo_formula is ? 
      AND concentracion_ing_activo is ? AND cantidad_unitaria is ? AND unidad is ? AND empaque_unitario is ? 
      AND precio is ? AND precio_unitario is ?", row["nombre"], row["ingrediente_activo"], row["tipo_formula"], row["concentracion_ing_activo"], 
      row["cantidad_unitaria"], row["unidad"], row["empaque_unitario"], row["precio"], row["precio_unitario"]).first() || new
      
      row["estado"] = true
      producto.attributes = row.to_hash.slice(*accessible_attributes)
      producto.save!
    end
  end
  
  #abrir el csv 
  def self.open_spreadsheet(file)
    case File.extname(file.original_filename)
      when ".csv" then Roo::Csv.new(file.path, nil, :ignore)
      when ".xls" then Roo::Excel.new(file.path, nil, :ignore)
      when ".xlsx" then Roo::Excelx.new(file.path, nil, :ignore)
      else raise "Unknown file type: #{file.original_filename}"
    end
  end
  
  #limpiar caracteres y valores antes de guardar
  def self.limpiar_row(fila)
    if (!fila["precio"].nil?)
      fila["precio"] = fila["precio"].gsub(/[^0-9]/i, '')
      boolPrecio = !fila["precio"].nan?
  	  fila["precio"] = boolPrecio ? Float(fila["precio"]) : 0.0
    else
      fila["precio"] =0.0
    end
    
    if(!fila["precio_unitario"].nil?)
      fila["precio_unitario"] = fila["precio_unitario"].gsub(/[^0-9]/i, '')
  	  boolPrecioUnitario = !fila["precio_unitario"].nan?
  	  fila["precio_unitario"] = boolPrecioUnitario ? Float(fila["precio_unitario"]) : 0.0
    else
      fila["precio_unitario"] =0.0
    end
    
    if(!fila["concentracion_ing_activo"].nil?)
      fila["concentracion_ing_activo"] = fila["concentracion_ing_activo"].gsub(/[^0-9]/i, '')
  	  boolConcActiva = !fila["concentracion_ing_activo"].nan?
  	  fila["concentracion_ing_activo"] = boolConcActiva ? Float(fila["concentracion_ing_activo"]) : 0.0
    else
      fila["concentracion_ing_activo"] =0.0
    end
	  
    
	  fila["estado"] = true
    return fila
  end

end

class String
  def nan?
    self !~ /^\s*[+-]?((\d+_?)*\d+(\.(\d+_?)*\d+)?|\.(\d+_?)*\d+)(\s*|([eE][+-]?(\d+_?)*\d+)\s*)$/
  end
end

app/controllers/productos_controller.rb
class ProductosController < ApplicationController

  # GET /productos
  # GET /productos.json
  def index
    
    if params[:query].present?
      @productos = Producto.search(params)
    else
      @productos = Producto.paginate(:page => params[:page])
    end
    
    #aca debo buscar los proveedores y categorias_producto y setearlos como arrays asi en la vista no consulto solo busco sobre este array 
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @productos }
    end
  end

  # GET /productos/1
  # GET /productos/1.json
  def show
    @producto = Producto.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @producto }
    end
  end

  # GET /productos/new
  # GET /productos/new.json
  def new
    @producto = Producto.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @producto }
    end
  end

  # GET /productos/1/edit
  def edit
    @producto = Producto.find(params[:id])
  end

  # POST /productos
  # POST /productos.json
  def create
    @producto = Producto.new(params[:producto])

    respond_to do |format|
      if @producto.save
        format.html { redirect_to @producto, notice: 'Producto was successfully created.' }
        format.json { render json: @producto, status: :created, location: @producto }
      else
        format.html { render action: "new" }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /productos/1
  # PUT /productos/1.json
  def update
    @producto = Producto.find(params[:id])

    respond_to do |format|
      if @producto.update_attributes(params[:producto])
        format.html { redirect_to @producto, notice: 'Producto was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /productos/1
  # DELETE /productos/1.json
  def destroy
    @producto = Producto.find(params[:id])
    @producto.destroy

    respond_to do |format|
      format.html { redirect_to productos_url }
      format.json { head :no_content }
    end
  end
  
  def importar
  end
  
  def importar_post
    if (!params[:file] )
      redirect_to importar_productos_path, alert: "No selecciono un archivo"      
    else
      Producto.importar_post(params[:file])
      redirect_to productos_path, notice: "Productos importados."      
    end

  end
end

app/helpers/productos_helper.rb
module ProductosHelper
	def order_colunm(column , title = nil)
		 title ||= column.titleize
		 direction = (column == params[:sort] && params[:direction] == "asc") ? "desc" : "asc"
		 link_to title, :sort => column, :direction => direction
	end
end

app/views/productos/_form.html.erb
<%= form_for(@producto) do |f| %>
  <% if @producto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@producto.errors.count, "error") %> prohibited this producto from being saved:</h2>

      <ul>
      <% @producto.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :"Proveedor" %><br />
	<%= select("producto", "proveedor_id", Proveedor.all.collect {|p| [ p.nombre, p.id ] }, {:include_blank => 'Ninguno'}) %>
  </div>
  <div class="field">
    <%= f.label :"Categoria Producto" %><br />
	<%= select("producto", "categoria_producto_id", CategoriaProducto.all.collect {|p| [ p.nombre, p.id ] }, {:include_blank => 'Ninguno'}) %>
  </div>
  <div class="field">
    <%= f.label :nombre %><br />
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :ingrediente_activo %><br />
    <%= f.text_field :ingrediente_activo %>
  </div>
  <div class="field">
    <%= f.label "Concentracion Ingrediente Activo" %><br />
    <%= f.text_field :concentracion_ing_activo %>
  </div>
  <div class="field">
    <%= f.label "Tipo Formulacion" %><br />
    <%= f.text_field :tipo_formula %>
  </div>
  <div class="field">
    <%= f.label "Cantidad Unitaria" %><br />
    <%= f.text_field :cantidad_unitaria %>
  </div>
  <div class="field">
    <%= f.label "Unidad" %><br />
    <%= f.text_field :unidad %>
  </div>
  <div class="field">
    <%= f.label "Empaque Unitario" %><br />
    <%= f.text_field :empaque_unitario %>
  </div>  
  <div class="field">
    <%= f.label :precio %><br />
    <%= f.text_field :precio %>
  </div>
  <div class="field">
    <%= f.label :precio_unitario %><br />
    <%= f.text_field :precio_unitario %>
  </div>
  <div class="field">
    <%= f.label "Ultima Actualizacion" %><br />
    <%= f.text_field :ultimo_update %>
  </div>
  <div class="field">
    <%= f.label :estado %><br />
    <%= f.check_box :estado %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/productos/edit.html.erb
<h1>Editing producto</h1>

<%= render 'form' %>

<%= link_to 'Show', @producto %> |
<%= link_to 'Back', productos_path %>

app/views/productos/importar.html.erb
<h2>Importar Productos</h2>

<%= form_tag importar_post_productos_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Importar" %>
<% end %>

app/views/productos/index.html.erb
<h1>Listing productos</h1>
<%= link_to 'Importar', importar_productos_path %>
<%= link_to 'New Producto', new_producto_path %>
<div>
	<%= form_tag productos_path, method: :get do %>
  		<p>
    		<%= text_field_tag :query, params[:query] %>
			<%= submit_tag "Buscar", name: nil %>
  	  	</p>
	<% end %>
</div>
<table>
  <tr>
    <th><%= order_colunm "proveedor_id" ,"Proveedor"%></th>
    <th><%= order_colunm  "categoria_producto_id",  "Categoria Producto" %></th>
    <th><%=  order_colunm "nombre", "Nombre" %></th>
    <th><%=  order_colunm "ingrediente_activo","Ingrediente activo" %></th>
    <th><%=  order_colunm "concentracion_ing_activo","Concentracion Ing. activo" %></th>
    <th><%=  order_colunm "tipo_formula","Tipo Formulacion"%></th>
    <th><%=  order_colunm "cantidad_unitaria","Cantidad Unitaria" %></th>	
    <th><%=  order_colunm "unidad","Unidad" %></th>	
    <th><%=  order_colunm "empaque_unitario","Empaque Unitario" %></th>	
    <th><%=  order_colunm "precio","Precio" %></th>
    <th><%=  order_colunm "precio_unitario","Precio Unitario" %></th>	
    <th><%=  order_colunm "ultimo_update","Ultima Actualizacion" %></th>
    <th><%=  order_colunm "estado","Estado" %></th>
    <th colspan="3">Opciones</th>
  </tr>

<% @productos.each do |producto| %>
  <tr>
	<td> 
				<!-- URGENTE SACAR ESTAS DOS CONSULTAS DE ACA!!!!! deben irse al controller en el index action -->
				<% if(false) %>
		<% if(producto.proveedor)%>
		<%= producto.proveedor.nombre %>
		<% end %>
	</td>
    <td>
		<% if(producto.categoria_producto)%>
		<%= producto.categoria_producto.nombre %>
		<% end %>
				<% end %>
					
	</td>
	<td></td>
    <td><%= producto.nombre %></td>
    <td><%= producto.ingrediente_activo %></td>
    <td><%= producto.concentracion_ing_activo %></td>
    <td><%= producto.tipo_formula %></td>
    <td><%= producto.cantidad_unitaria %></td>
	<td><%= producto.unidad %></td>
    <td><%= producto.empaque_unitario %></td>	
    <td><%= producto.precio %></td>
    <td><%= producto.precio_unitario %></td>	
    <td><%= producto.ultimo_update %></td>
    <td><%= producto.estado %></td>
    <td><%= link_to 'Show', producto %></td>
    <td><%= link_to 'Edit', edit_producto_path(producto) %></td>
    <td><%= link_to 'Destroy', producto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>
<div class="digg_pagination">
	<%= will_paginate @productos %>
</div>

app/views/productos/new.html.erb
<h1>New producto</h1>

<%= render 'form' %>

<%= link_to 'Back', productos_path %>

app/views/productos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id proveedor:</b>
  <%= @producto.proveedor_id %>
</p>

<p>
  <b>Id categoria producto:</b>
  <%= @producto.categoria_producto_id %>
</p>

<p>
  <b>Nombre:</b>
  <%= @producto.nombre %>
</p>

<p>
  <b>Ingrediente activo:</b>
  <%= @producto.ingrediente_activo %>
</p>

<p>
  <b>Concentracion ing activo:</b>
  <%= @producto.concentracion_ing_activo %>
</p>

<p>
  <b>Tipo Formulacion:</b>
  <%= @producto.tipo_formula %>
</p>

<p>
  <b>Cantidad Unitaria:</b>
  <%= @producto.cantidad_unitaria %>
</p>

<p>
  <b>Unidad:</b>
  <%= @producto.unidad %>
</p>

<p>
  <b>Empaque Unitario:</b>
  <%= @producto.empaque_unitario %>
</p>

<p>
  <b>Precio:</b>
  <%= @producto.precio %>
</p>

<p>
  <b>Precio Unitario:</b>
  <%= @producto.precio_unitario %>
</p>

<p>
  <b>Ultima Actualizacion:</b>
  <%= @producto.ultimo_update %>
</p>

<p>
  <b>Estado:</b>
  <%= @producto.estado %>
</p>


<%= link_to 'Edit', edit_producto_path(@producto) %> |
<%= link_to 'Back', productos_path %>