config/routes.rb
Precios::Application.routes.draw do

  resources :categoria_productos
  
  
  resources :productos do
    collection do 
      get :importar 
      post :importar_post
    end
  end

  resources :productos
  resources :proveedors
  resources :empresas

  devise_for :usuarios do get '/usuarios/sign_out' => 'devise/sessions#destroy', :path_prefix => 'my' end
  resources :usuarios
  match 'usuarios/:id' => 'usuarios#show'

  get "usuarios/index"
  get "home/index"

  root :to => 'home#index'

end

app/models/empresa.rb
class Empresa < ActiveRecord::Base
  attr_accessible :direccion, :estado, :nombre, :telefono
  has_many :usuarios
  validates :direccion, :nombre, :telefono, :presence => { :message => ": Ingrese un valor." }
end

app/controllers/empresas_controller.rb
class EmpresasController < ApplicationController
  handles_sortable_columns
  # GET /empresas
  # GET /empresas.json
  def index
    order = sortable_column_order
    @empresas = Empresa.order(order)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @empresas }
    end
  end

  # GET /empresas/1
  # GET /empresas/1.json
  def show
    @empresa = Empresa.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @empresa }
    end
  end

  # GET /empresas/new
  # GET /empresas/new.json
  def new
    @empresa = Empresa.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @empresa }
    end
  end

  # GET /empresas/1/edit
  def edit
    @empresa = Empresa.find(params[:id])
  end

  # POST /empresas
  # POST /empresas.json
  def create
    @empresa = Empresa.new(params[:empresa])

    respond_to do |format|
      if @empresa.save
        format.html { redirect_to @empresa, notice: 'Empresa was successfully created.' }
        format.json { render json: @empresa, status: :created, location: @empresa }
      else
        format.html { render action: "new" }
        format.json { render json: @empresa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /empresas/1
  # PUT /empresas/1.json
  def update
    @empresa = Empresa.find(params[:id])

    respond_to do |format|
      if @empresa.update_attributes(params[:empresa])
        format.html { redirect_to @empresa, notice: 'Empresa was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @empresa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /empresas/1
  # DELETE /empresas/1.json
  def destroy
    @empresa = Empresa.find(params[:id])
    @empresa.destroy

    respond_to do |format|
      format.html { redirect_to empresas_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/empresas_helper.rb
module EmpresasHelper
end

app/views/empresas/_form.html.erb
<%= form_for(@empresa) do |f| %>
  <% if @empresa.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@empresa.errors.count, "error") %> prohibited this empresa from being saved:</h2>

      <ul>
      <% @empresa.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br />
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :direccion %><br />
    <%= f.text_field :direccion %>
  </div>
  <div class="field">
    <%= f.label :telefono %><br />
    <%= f.text_field :telefono %>
  </div>
  <div class="field">
    <%= f.label :estado %><br />
    <%= f.check_box :estado %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/empresas/edit.html.erb
<h1>Editing empresa</h1>

<%= render 'form' %>

<%= link_to 'Show', @empresa %> |
<%= link_to 'Back', empresas_path %>

app/views/empresas/index.html.erb
<h1>Listing empresas</h1>

<table>
  <tr>
    <th>Nombre</th>
    <th>Direccion</th>
    <th>Telefono</th>
    <th>Estado</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @empresas.each do |empresa| %>
  <tr>
    <td><%= empresa.nombre %></td>
    <td><%= empresa.direccion %></td>
    <td><%= empresa.telefono %></td>
    <td><%= empresa.estado %></td>
    <td><%= link_to 'Show', empresa %></td>
    <td><%= link_to 'Edit', edit_empresa_path(empresa) %></td>
    <td><%= link_to 'Destroy', empresa, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Empresa', new_empresa_path %>

app/views/empresas/new.html.erb
<h1>New empresa</h1>

<%= render 'form' %>

<%= link_to 'Back', empresas_path %>

app/views/empresas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nombre:</b>
  <%= @empresa.nombre %>
</p>

<p>
  <b>Direccion:</b>
  <%= @empresa.direccion %>
</p>

<p>
  <b>Telefono:</b>
  <%= @empresa.telefono %>
</p>

<p>
  <b>Estado:</b>
  <%= @empresa.estado %>
</p>


<%= link_to 'Edit', edit_empresa_path(@empresa) %> |
<%= link_to 'Back', empresas_path %>