config/routes.rb
Precios::Application.routes.draw do

  resources :categoria_productos
  
  
  resources :productos do
    collection do 
      get :importar 
      post :importar_post
    end
  end

  resources :productos
  resources :proveedors
  resources :empresas

  devise_for :usuarios do get '/usuarios/sign_out' => 'devise/sessions#destroy', :path_prefix => 'my' end
  resources :usuarios
  match 'usuarios/:id' => 'usuarios#show'

  get "usuarios/index"
  get "home/index"

  root :to => 'home#index'

end

app/views/layouts/_admin.html.erb
<ul>
	<li class="active"><%= link_to 'Home', root_path %></li>

	<li><%= link_to 'Usuarios', usuarios_path %></li>
	<li><%= link_to 'Empresa', empresas_path %></li>
	<li><%= link_to 'Productos', productos_path %></li>	
	<li><%= link_to 'Categoria Productos', categoria_productos_path %></li>	
	<li><%= link_to 'Proveedor', proveedors_path %></li>	
	<%= render 'devise/menu/registration_items' %>
	<%= render 'devise/menu/login_items' %>
				
</ul>

app/views/layouts/_usuario.html.erb
<ul>
	<li class="active"><%= link_to 'Home', root_path %></li>
	
	<%= render 'devise/menu/registration_items' %>
	<%= render 'devise/menu/login_items' %>			
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <title>Precios</title>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
	<%= stylesheet_link_tag "style" %>
</head>
<body>
	<div id="header">
		<p class="notice"><%= notice %></p>
		<p class="alert"><%= alert %></p>
		<div id="menu">
			<%= render :partial=>"layouts/#{controller.sub_layout}" %>
		</div>
	</div>
	<div id="page">
		<!-- start content -->
		<div id="content">
			<%= yield %>
		</div>
	</div>
</body>
</html>